import Provider from "@components/Provider";
import { ReduxProvider } from "@components/ReduxProvider";
import "@styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Provider>{children}</Provider>
        </ReduxProvider>
      </body>
    </html>
  );
}
